theme: jekyll-theme-minimal
title:  pbasil.com
description:  >-
<Hello there! If you have any questions or proposals related to my area of interest, feel free to reach out to me via LinkedIn or email.>
url: "https://pbasil.com"
